version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: staax_db
    environment:
      POSTGRES_USER: staax
      POSTGRES_PASSWORD: staax_password
      POSTGRES_DB: staax_db
    ports:
      - "5432:5432"
    volumes:
      - staax_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: staax_redis
    ports:
      - "6379:6379"
    volumes:
      - staax_redisdata:/data
    restart: unless-stopped

volumes:
  staax_pgdata:
  staax_redisdata:
