"""add_missing_indexes

Revision ID: b0a824b9af2f
Revises: 66925d412955
Create Date: 2026-04-22 19:57:30.228081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a824b9af2f'
down_revision: Union[str, None] = '66925d412955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invex_watchlist')
    op.drop_table('invex_holdings')
    op.drop_index('uq_bot_signal', table_name='bot_signals', postgresql_where='(candle_timestamp IS NOT NULL)')
    op.drop_table('bot_signals')
    op.drop_table('system_state')
    op.drop_table('invex_sips')
    op.drop_table('invex_ipo_orders')
    op.drop_index('ix_event_log_ts', table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('bots')
    op.drop_table('invex_ipo_bots')
    op.drop_table('algorithms_registry')
    op.drop_table('invex_mf_holdings')
    op.drop_table('invex_portfolio_snapshots')
    op.drop_table('invex_equity_transactions')
    op.drop_index('ix_bot_orders_bot_id', table_name='bot_orders')
    op.drop_index('ix_bot_orders_status', table_name='bot_orders')
    op.drop_table('bot_orders')
    op.drop_index('ix_execution_logs_algo_id', table_name='execution_logs')
    op.drop_index('ix_execution_logs_order_id', table_name='execution_logs')
    op.drop_index('ix_execution_logs_timestamp', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_order_audit_log_algo_id', table_name='order_audit_log')
    op.drop_index('ix_order_audit_log_order_id', table_name='order_audit_log')
    op.drop_table('order_audit_log')
    op.drop_table('invex_sip_executions')
    op.drop_table('invex_sectors')
    op.alter_column('algo_legs', 'reentry_max_sl',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('algo_legs', 'reentry_max_tp',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('algo_legs', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_algo_legs_algo_id'), 'algo_legs', ['algo_id'], unique=False)
    op.alter_column('algo_states', 'sl_reentry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('algo_states', 'tp_reentry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_algo_states_account_id'), 'algo_states', ['account_id'], unique=False)
    op.create_index(op.f('ix_algo_states_algo_id'), 'algo_states', ['algo_id'], unique=False)
    op.create_index(op.f('ix_algo_states_status'), 'algo_states', ['status'], unique=False)
    op.create_index(op.f('ix_algo_states_trading_date'), 'algo_states', ['trading_date'], unique=False)
    # Create the enum type first (may already exist — ignore error)
    op.execute("DO $$ BEGIN CREATE TYPE strategytype AS ENUM ('white_box', 'black_box'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.alter_column('algos', 'strategy_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('white_box', 'black_box', name='strategytype'),
               existing_nullable=True,
               postgresql_using="strategy_type::strategytype")
    op.create_index(op.f('ix_algos_account_id'), 'algos', ['account_id'], unique=False)
    op.create_index(op.f('ix_grid_entries_account_id'), 'grid_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_grid_entries_algo_id'), 'grid_entries', ['algo_id'], unique=False)
    op.create_index(op.f('ix_grid_entries_status'), 'grid_entries', ['status'], unique=False)
    op.create_index(op.f('ix_grid_entries_trading_date'), 'grid_entries', ['trading_date'], unique=False)
    op.alter_column('market_holidays', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('market_holidays', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('market_holidays_date_segment_key', 'market_holidays', type_='unique')
    op.alter_column('orders', 'tsl_activated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'ttp_activated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_algo_id'), 'trades', ['algo_id'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_trading_date'), 'trades', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trading_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_algo_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.alter_column('orders', 'ttp_activated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'tsl_activated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('market_holidays_date_segment_key', 'market_holidays', ['date', 'segment'])
    op.alter_column('market_holidays', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_holidays', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f('ix_grid_entries_trading_date'), table_name='grid_entries')
    op.drop_index(op.f('ix_grid_entries_status'), table_name='grid_entries')
    op.drop_index(op.f('ix_grid_entries_algo_id'), table_name='grid_entries')
    op.drop_index(op.f('ix_grid_entries_account_id'), table_name='grid_entries')
    op.drop_index(op.f('ix_algos_account_id'), table_name='algos')
    op.alter_column('algos', 'strategy_type',
               existing_type=sa.Enum('white_box', 'black_box', name='strategytype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_algo_states_trading_date'), table_name='algo_states')
    op.drop_index(op.f('ix_algo_states_status'), table_name='algo_states')
    op.drop_index(op.f('ix_algo_states_algo_id'), table_name='algo_states')
    op.drop_index(op.f('ix_algo_states_account_id'), table_name='algo_states')
    op.alter_column('algo_states', 'tp_reentry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('algo_states', 'sl_reentry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_algo_legs_algo_id'), table_name='algo_legs')
    op.alter_column('algo_legs', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('algo_legs', 'reentry_max_tp',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('algo_legs', 'reentry_max_sl',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('invex_sectors',
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sector', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', name='invex_sectors_pkey')
    )
    op.create_table('invex_sip_executions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('broker_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'placed'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_sip_executions_pkey')
    )
    op.create_table('order_audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('algo_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('grid_entry_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('from_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('fill_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('broker_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_practix', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='order_audit_log_pkey')
    )
    op.create_index('ix_order_audit_log_order_id', 'order_audit_log', ['order_id'], unique=False)
    op.create_index('ix_order_audit_log_algo_id', 'order_audit_log', ['algo_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('algo_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('algo_tag', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grid_entry_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_practix', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='execution_logs_account_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['algo_id'], ['algos.id'], name='execution_logs_algo_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='execution_logs_order_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='execution_logs_pkey')
    )
    op.create_index('ix_execution_logs_timestamp', 'execution_logs', ['timestamp'], unique=False)
    op.create_index('ix_execution_logs_order_id', 'execution_logs', ['order_id'], unique=False)
    op.create_index('ix_execution_logs_algo_id', 'execution_logs', ['algo_id'], unique=False)
    op.create_table('bot_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expiry', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('lots', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
    sa.Column('broker_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bot_orders_pkey')
    )
    op.create_index('ix_bot_orders_status', 'bot_orders', ['status'], unique=False)
    op.create_index('ix_bot_orders_bot_id', 'bot_orders', ['bot_id'], unique=False)
    op.create_table('invex_equity_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('broker_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_equity_transactions_pkey')
    )
    op.create_table('invex_portfolio_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('portfolio_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('invested_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cash_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('day_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_portfolio_snapshots_pkey')
    )
    op.create_table('invex_mf_holdings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fund_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('isin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('units', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('nav', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('invested_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_mf_holdings_pkey')
    )
    op.create_table('algorithms_registry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('algo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('strategy_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('exchange_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['algo_id'], ['algos.id'], name='algorithms_registry_algo_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='algorithms_registry_pkey'),
    sa.UniqueConstraint('algo_id', name='algorithms_registry_algo_id_key')
    )
    op.create_table('invex_ipo_bots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('yearly_open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prev_year_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prev_year_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upp1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpp1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trade_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'10000'::double precision"), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'watching'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_practix', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_ipo_bots_pkey')
    )
    op.create_table('bots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('expiry', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('indicator', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('timeframe_mins', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('lots', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('channel_candles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tt_lookback', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('channel_tf', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_practix', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('pinescript_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bots_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('event_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('msg', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('algo_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('algo_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_log_pkey')
    )
    op.create_index('ix_event_log_ts', 'event_log', ['ts'], unique=False)
    op.create_table('invex_ipo_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
    sa.Column('broker_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_ipo_orders_pkey')
    )
    op.create_table('invex_sips',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('frequency_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frequency_date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_invested', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('total_units', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_sips_pkey')
    )
    op.create_table('system_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kill_switch_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('kill_switch_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('positions_squared', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('orders_cancelled', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('kill_switch_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('killed_account_ids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_state_pkey')
    )
    op.create_table('bot_signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('bot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('signal_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('instrument_token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'fired'::character varying"), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('candle_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('instrument', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('expiry', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trigger_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bot_order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='bot_signals_bot_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='bot_signals_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bot_signals_pkey')
    )
    op.create_index('uq_bot_signal', 'bot_signals', ['bot_id', 'signal_type', 'direction', 'candle_timestamp'], unique=True, postgresql_where='(candle_timestamp IS NOT NULL)')
    op.create_table('invex_holdings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('isin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ltp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('day_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_holdings_pkey')
    )
    op.create_table('invex_watchlist',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('price_alert_above', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_alert_below', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rsi_alert_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earnings_alert', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invex_watchlist_pkey')
    )
    # ### end Alembic commands ###
